apiVersion: v1
kind: ReplicationController
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: javasampleappwar
    spec:
      containers:
      - image: naresh240/javasampleappwar
        name: javasampleappwar
        ports:
        - name: javasampleappwar
          containerPort: 8081
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: javasampleappwar
  name: javasampleappwar
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    name: javasampleappwar